pub static MAP_NAMES: &[(&str, &str)] = &[
    ("PVP03_HerefordBase_Warmup", "Hereford Base"),
    ("RussianCafe", "Kafe Dostoyevsky"),
    ("HOUSE", "House"),
    ("HarvardFaculty", "Bartlett University"),
    ("Yatch", "Yacht"),
    ("THEMEPARK", "Theme Park"),
    ("Ibiza", "Coastline"),
    ("!!AUSTRALIA", "Outback"),
    ("PVP01_House_Warmup", "House"),
    ("ITALY", "Villa"),
    ("RUSSIAN CAFE", "Kafe Dostoyevsky"),
    ("ThemePark", "Theme Park"),
    ("TEMPLE", "Skyscraper"),
    ("Gym-09-Kanal", "Kanal"),
    ("PVP06_Yatch_Warmup", "Yacht"),
    ("PVP13_Border_TDM_SecureArea", "Border"),
    ("Gym-04-ClubHouse", "Club House"),
    ("PVP02_Oregon_Warmup", "Oregon"),
    ("IBIZA", "Coastline"),
    ("CLUB HOUSE", "Club House"),
    ("PLANE", "Presidential Plane"),
    ("OREGON", "Oregon"),
    ("PVP05_Plane_Warmup", "Presidential Plane"),
    ("PVP09_Kanal_Warmup", "Kanal"),
    ("CONSULATE", "Consulate"),
    ("PVP10_Chalet_Warmup", "Chalet"),
    ("MOROCCO", "Fortress"),
    ("Plane", "Presidential Plane"),
    ("PVP08_Bank_Warmup", "Bank"),
    ("Gym-08-Bank", "Bank"),
    ("Gym-01-House", "House"),
    ("CHALET", "Chalet"),
    ("Gym-10-Chalet", "Chalet"),
    ("PVP11_HarvardFaculty_Warmup", "Bartlett University"),
    (" HarvardFaculty", "Bartlett University"),
    ("PVP04_ClubHouse_Warmup", "Club House"),
    ("BANK", "Bank"),
    ("Gym-07-Consulate", "Consulate"),
    ("Italy", "Villa"),
    ("Gym-03-HerefordBase", "Hereford Base"),
    ("YACHT", "Yacht"),
    ("Gym-12-RussianCafe", "Kafe Dostoyevsky"),
    ("FAVELA", "Favela"),
    ("KANAL", "Kanal"),
    ("Gym-11-HarvardFaculty", "Bartlett University"),
    ("Morocco", "Fortress"),
    ("HEREFORD", "Hereford Base"),
    ("HerefordRework", "Hereford Base - Rework"),
    ("Gym-02-Oregon", "Oregon"),
    ("Gym-14-Favela", "Favela"),
    ("BORDER", "Border"),
    ("Gym-05-Plane", "Presidential Plane"),
    ("HARVARD FACULTY", "Bartlett University"),
    ("HerefordBase", "Hereford Base"),
    ("PVP12_RussianCafe_Warmup", "Kafe Dostoyevsky"),
    ("Australia", "Outback"),
    ("Temple", "Skyscraper"),
    ("ClubHouse", "Club House"),
    ("TOWER", "Tower"),
    ("Gym-13-Border", "Border"),
    ("Gym-06-Yatch", "Yacht"),
    ("PVP07_Consulate_Warmup", "Consulate"),
];
pub static GAMETYPE_NAMES: &[(&str, &str)] = &[
    ("TERROHUNT - DAY", "Elimination - Day"),
    ("TERROHUNT - NIGHT", "Elimination - Night"),
    ("ATTACK - DAY", "Attack - Day"),
    ("ATTACK - NIGHT", "Attack - Night"),
    ("DEFEND - DAY", "Defend - Day"),
    ("DEFEND - NIGHT", "Defend - Night"),
];
