pub static SEASON_NAMES: &[&str] = &[
    "Y1S0 Vanilla",
    "Y1S1 Black Ice",
    "Y1S2 Dust Line",
    "Y1S3 Skull Rain",
    "Y1S4 Red Crow",
    "Y2S1 Velvet Shell",
    "Y2S2 Health",
    "Y2S3 Blood Orchid",
    "Y2S4 White Noise",
    "Y3S1 Chimera",
    "Y3S2 Para Bellum",
    "Y3S3 Grim Sky",
    "Y3S4 Wind Bastion",
    "Y4S1 Burnt Horizon",
    "Y4S2 Phantom Sight",
    "Y4S3 Ember Rise",
    "Y4S4 Shifting Tides",
    "Y5S1 Void Edge",
    "Y5S2 Steel Wave",
    "Y5S3 Shadow Legacy",
    "Y5S4 Neon Dawn",
    "Y6S1 Crimson Heist",
    "Y6S2 North Star",
    "Y6S3 Crystal Guard",
    "Y6S4 High Calibre",
    "Y7S1 Demon Veil",
    "Y7S2 Vector Glare",
    "Y7S4 Solar Raid",
];
pub const SEASON_NAMES_COUNT: usize = 28;
