from typing import Protocol


class Reporter(Protocol):
    def update(self, text: str) -> None: ...
    def fail(self, text: str) -> None: ...
    def progress(self, fraction: float) -> None: ...


class NullReporter:
    def update(self, text: str) -> None: ...

    def fail(self, text: str) -> None: ...

    def progress(self, fraction: float) -> None: ...
